[package]
name = "sketches"
version = "0.1.0"
authors = ["demi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou="0.15.0"

[workspace]
members = ["jelly", "waving_sine"]